# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param simulator.modelsimInstallPath C:/Program%20Files%20(x86)/ModelSim
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {Synth 8-3848}  -string {{WARNING: [Synth 8-3848] Net PJTAG_TDO in module/entity processing_system7_v5_5_processing_system7 does not have driver. [c:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/AXI_JTAG_TEST/AXI_JTAG_TEST.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0_1/hdl/verilog/processing_system7_v5_5_processing_system7.v:298]}}  -suppress 

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/JTAG_IF.cache/wt [current_project]
set_property parent.project_path C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/JTAG_IF.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
set_property ip_repo_paths C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/ip_repo [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/src/serializer.vhd
  C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/src/deserializer.vhd
  C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/src/timer.vhd
  C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/src/if_in.vhd
  C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/src/if_out.vhd
  C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/src/fifo.vhd
  C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/src/jtag_if_top.vhd
}
read_xdc C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/synth/jtag_if.xdc
set_property used_in_implementation false [get_files C:/Users/Max/Documents/Elektrotechnik/dis-2014-2015/DIS_Seminar/Project/JTAG_IF/synth/jtag_if.xdc]

catch { write_hwdef -file jtag_if.hwdef }
synth_design -top jtag_if -part xc7z020clg484-1 -flatten_hierarchy none
write_checkpoint jtag_if.dcp
catch { report_utilization -file jtag_if_utilization_synth.rpt -pb jtag_if_utilization_synth.pb }
